<?php
/**
 * Kohevo Studio — Builder shell host page.
 *
 *   GET /plugins/studio-builder/admin/builder.php?page=<id>
 *
 * Serves only the empty application shell: the prebuilt React bundle, its
 * stylesheet and a small non-executable JSON boot block (endpoint URLs, the
 * page id, the session CSRF token). The page document itself is NOT embedded:
 * the builder always loads it from the server through the command/query API,
 * so a reload reconstructs the editor exclusively from the canonical revision.
 *
 * Access runs the full application pipeline up front (tenant ->
 * authentication -> studio-builder entitlement -> studio-builder.edit -> page
 * ownership) so an unauthorized user never even receives the shell.
 */

declare(strict_types=1);

require_once dirname(__DIR__, 3) . '/config.php';

use Slate\Module\StudioBuilder\Application\StudioActor;
use Slate\Module\StudioBuilder\Exception\StudioException;
use Slate\Module\StudioBuilder\Http\StudioCanvasPolicy;
use Slate\Module\StudioBuilder\Runtime\StudioLog;
use Slate\Module\StudioBuilder\Runtime\StudioRuntimeFactory;

Auth::require();

$sbPageId = filter_var($_GET['page'] ?? null, FILTER_VALIDATE_INT, ['options' => ['min_range' => 1]]);
$sbStatus = 200;
$sbTitle  = '';
if ($sbPageId === false || $sbPageId === null) {
    $sbStatus = 404;
} else {
    try {
        $sbState = StudioRuntimeFactory::build()->app->loadEditorDocument(StudioActor::fromCurrentSession(), $sbPageId);
        $sbTitle = (string) $sbState['page']['title'];
        unset($sbState);
    } catch (StudioException $e) {
        $sbStatus = $e->httpStatus();
        if ($sbStatus >= 500) {
            StudioLog::failure('builder', 'shell', $e);
        }
    } catch (\Throwable $e) {
        StudioLog::failure('builder', 'shell', $e);
        $sbStatus = 500;
    }
}

header('Cache-Control: no-store, no-cache, must-revalidate, max-age=0');
header('Pragma: no-cache');
header('X-Robots-Tag: noindex, nofollow');
header('Referrer-Policy: same-origin');
header(
    "Content-Security-Policy: default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; "
    . "img-src 'self' https: data:; font-src 'self' https: data:; connect-src 'self'; frame-src 'self'; "
    . "object-src 'none'; base-uri 'self'; form-action 'self'; frame-ancestors 'self'",
    true
);

$sbPagesUrl = plugin_url('studio-builder', 'admin/index.php');

// The builder is a full-screen app: no floating language-switcher widget on top of its controls.
if (!defined('SLATE_NO_LANG_SWITCHER')) {
    define('SLATE_NO_LANG_SWITCHER', true);
}

if ($sbStatus !== 200) {
    http_response_code(in_array($sbStatus, [401, 403, 404], true) ? $sbStatus : 500);
    $sbMessage = match ($sbStatus) {
        403     => __('studio_builder_forbidden', 'You do not have access to edit this page.'),
        404     => __('studio_builder_not_found', 'This page was not found.'),
        default => __('studio_builder_unavailable', 'The builder could not be opened right now.'),
    };
    echo '<!DOCTYPE html><html lang="' . e(\Slate\Services\I18n\I18n::currentLocale()) . '"><head><meta charset="utf-8"><meta name="robots" content="noindex,nofollow">'
        . '<title>' . e(__('studio_builder', 'Kohevo Studio')) . '</title></head><body style="font-family:system-ui,sans-serif;padding:2rem">'
        . '<p>' . e($sbMessage) . '</p><p><a href="' . e($sbPagesUrl) . '">' . e(__('studio_back_to_pages', 'Back to Studio pages')) . '</a></p></body></html>';
    exit;
}

$sbAssetDir = dirname(__DIR__) . '/assets/builder';
$sbVersion  = (string) max(
    (int) (@filemtime($sbAssetDir . '/builder.js') ?: 0),
    (int) (@filemtime($sbAssetDir . '/builder.css') ?: 0),
    (int) (@filemtime(__FILE__) ?: 0)
);
$sbMediaPicker = class_exists('PluginLoader') && PluginLoader::isActive('media-library') && Auth::can('media.view');
// Phase 7: the AI assistant entry point (the MCP gateway's admin chat) is offered only
// when that module is active and the signed-in admin may open it. The chat prepares
// DRAFT revisions; publishing stays this builder's own Publish action.
$sbAssistantUrl = class_exists('PluginLoader') && PluginLoader::isActive('mcp-gateway') && (Auth::can('mcp-gateway.manage') || Auth::isSuperAdmin())
    ? plugin_url('mcp-gateway', 'admin/chat.php')
    : null;

$sbAllPages = [];
try {
    $sbAllPagesList = StudioRuntimeFactory::build()->app->listPages(StudioActor::fromCurrentSession());
    foreach ($sbAllPagesList as $p) {
        $sbAllPages[] = [
            'id'           => (int) $p['id'],
            'title'        => (string) $p['title'],
            'slug'         => (string) ($p['slug'] ?? ''),
            'is_published' => !empty($p['is_published']),
        ];
    }
} catch (\Throwable $e) {
    // Graceful fallback
}

$sbBoot = [
    'pageId'     => $sbPageId,
    'allPages'   => $sbAllPages,
    'apiUrl'     => plugin_url('studio-builder', 'admin/api.php'),
    'canvasUrl'  => plugin_url('studio-builder', 'admin/canvas.php'),
    'previewUrl' => plugin_url('studio-builder', 'admin/preview.php'),
    'pagesUrl'   => $sbPagesUrl,
    'siteUrl'    => rtrim((string) SLATE_URL, '/'),
    'csrfToken'  => csrf_token(),
    'canvasSandbox' => StudioCanvasPolicy::IFRAME_SANDBOX,
    'mediaPicker'   => $sbMediaPicker,
    'builderUrl'    => plugin_url('studio-builder', 'admin/builder.php'),
    'brandingUrl'   => rtrim((string) SLATE_URL, '/') . '/admin/settings.php?tab=branding',
    'assistantUrl'  => $sbAssistantUrl,
    // Phase 8B: translated builder strings (the UI's setMessages(); English is the UI's own fallback).
    'messages'      => [
        'import_source'          => __('studio_ui_import_source', 'Import from'),
        'import_source_package'  => __('studio_ui_import_source_package', 'Kohevo package (.json)'),
        'import_source_html'     => __('studio_ui_import_source_html', 'HTML/CSS'),
        'import_html_hint'       => __('studio_ui_import_html_hint', 'Choose an HTML file and, optionally, a CSS file. The page structure is converted into Studio blocks: scripts, forms, embeds and unsupported styling are removed, external images are never downloaded, and nothing is published.'),
        'import_html_file'       => __('studio_ui_import_html_file', 'HTML file'),
        'import_css_file'        => __('studio_ui_import_css_file', 'CSS file (optional)'),
        'import_title'           => __('studio_ui_import_title', 'Page title'),
        'import_slug'            => __('studio_ui_import_slug', 'Page address (slug)'),
        'import_html_conversion' => __('studio_ui_import_html_conversion', '{stripped} element(s) removed for security, {unsupported} unsupported element(s) and {hidden} hidden element(s) left out.'),
        'source_empty'           => __('studio_ui_source_empty', 'The file is empty.'),
        'source_too_large'       => __('studio_ui_source_too_large', 'This file is too large to import.'),
        'seo_title_label' => __('studio_ui_seo_title_label', 'SEO title'),
        'seo_description_label' => __('studio_ui_seo_description_label', 'Meta description'),
        'seo_canonical_label' => __('studio_ui_seo_canonical_label', 'Canonical URL'),
        'seo_canonical_hint' => __('studio_ui_seo_canonical_hint', 'Optional. A path on this site (/about) or a full address on this site. Leave empty to use this page\'s own address. Other websites are ignored: Studio never declares another domain as canonical.'),
        'seo_canonical_invalid' => __('studio_ui_seo_canonical_invalid', 'Enter a path starting with / or a full http(s) address.'),
        'seo_og_image_label' => __('studio_ui_seo_og_image_label', 'Social share image'),
        'seo_og_image_hint' => __('studio_ui_seo_og_image_hint', 'Shown when the page is shared. Choose an image from your media library.'),
        'seo_robots_label' => __('studio_ui_seo_robots_label', 'Search engine visibility'),
        'seo_draft_note' => __('studio_ui_seo_draft_note', 'Search settings belong to the draft. They go live only when you publish.'),
        'seo_remove_image' => __('studio_ui_seo_remove_image', 'Remove image'),
        'view_mode' => __('studio_ui_view_mode', 'View mode'),
        'mode_edit' => __('studio_ui_mode_edit', 'Edit'),
        'mode_edit_hint' => __('studio_ui_mode_edit_hint', 'Edit mode: select, drag and edit on the canvas'),
        'mode_preview' => __('studio_ui_mode_preview', 'Preview'),
        'mode_preview_hint' => __('studio_ui_mode_preview_hint', 'Editor preview: the canvas becomes read-only and the builder stays open'),
        'mode_visitor' => __('studio_ui_mode_visitor', 'Visitor'),
        'mode_visitor_hint' => __('studio_ui_mode_visitor_hint', 'Visitor preview: the page as a visitor sees it, with minimal editor chrome'),
        'inspector_show' => __('studio_ui_inspector_show', 'Show the editor panel'),
        'inspector_hide' => __('studio_ui_inspector_hide', 'Hide the editor panel for a full-width canvas'),
        'open_new_tab' => __('studio_ui_open_new_tab', 'Open in a new tab'),
        'visitor_preview' => __('studio_ui_visitor_preview', 'Visitor preview'),
        'back_to_editing' => __('studio_ui_back_to_editing', 'Back to editing'),
        'reload' => __('studio_ui_reload', 'Reload'),
        'visitor_preview_stale' => __('studio_ui_visitor_preview_stale', 'The preview shows the last saved draft. Save to see your latest edits.'),
        'save_draft' => __('studio_ui_save_draft', 'Save draft'),
        'breadcrumb' => __('studio_ui_breadcrumb', 'Selection path'),
        'page' => __('studio_ui_page', 'Page'),
        'grid' => __('studio_ui_grid', 'Grid'),
        'grid_toggle' => __('studio_ui_grid_toggle', 'Show or hide the column grid'),
        'bulk_actions' => __('studio_ui_bulk_actions', 'Actions for the selected layers'),
        'bulk_selected' => __('studio_ui_bulk_selected', '{count} selected'),
        'tab_add_title' => __('studio_ui_tab_add_title', 'Add Blocks & Elements'),
        'tab_settings_title' => __('studio_ui_tab_settings_title', 'Page Settings & SEO'),
        'sheet_add' => __('studio_ui_sheet_add', 'Add Element'),
        'sheet_layers' => __('studio_ui_sheet_layers', 'Page Layers'),
        'sheet_edit_section' => __('studio_ui_sheet_edit_section', 'Edit Section'),
        'sheet_edit_block' => __('studio_ui_sheet_edit_block', 'Edit Block'),
        'sheet_library' => __('studio_ui_sheet_library', 'Templates & Presets'),
        'sheet_page_settings' => __('studio_ui_sheet_page_settings', 'Page Settings'),
        'close_panel' => __('studio_ui_close_panel', 'Close panel'),
        'inspector_empty_desc' => __('studio_ui_inspector_empty_desc', 'Select any section or block on the canvas or from the Layers tab to customize typography, layout, spacing, colors, and styling.'),
        'view_layers' => __('studio_ui_view_layers', 'View Layers'),
        'add_elements' => __('studio_ui_add_elements', 'Add Elements'),
        'open_editor_panel' => __('studio_ui_open_editor_panel', 'Open Editor Panel'),
        'panel_word' => __('studio_ui_panel_word', 'Panel'),
        'tab_add' => __('studio_ui_tab_add', 'Add'),
        'tab_layers' => __('studio_ui_tab_layers', 'Layers'),
        'tab_library' => __('studio_ui_tab_library', 'Library'),
        'tab_settings' => __('studio_ui_tab_settings', 'Settings'),
        'sheet_edit_named' => __('studio_ui_sheet_edit_named', 'Edit {label}'),
        'switch_page_title' => __('studio_ui_switch_page_title', 'Switch page in builder'),
        'switch_page' => __('studio_ui_switch_page', 'Switch page'),
        'undo_title' => __('studio_ui_undo_title', 'Undo (Ctrl+Z)'),
        'redo_title' => __('studio_ui_redo_title', 'Redo (Ctrl+Y)'),
        'save_draft_title' => __('studio_ui_save_draft_title', 'Save draft (Ctrl+S)'),
        'update_live_page' => __('studio_ui_update_live_page', 'Update live page'),
        'publish_page_title' => __('studio_ui_publish_page_title', 'Publish page'),
        'more_actions' => __('studio_ui_more_actions', 'More actions'),
        'import_export' => __('studio_ui_import_export', 'Import / Export'),
        'preview_link' => __('studio_ui_preview_link', 'Preview link'),
        'canvas_label' => __('studio_ui_canvas_label', 'Canvas'),
        'canvas_after_save' => __('studio_ui_canvas_after_save', 'canvas updates after save'),
        'reload_canvas' => __('studio_ui_reload_canvas', 'Reload canvas'),
        'show_sidebar' => __('studio_ui_show_sidebar', 'Show editor sidebar'),
        'hide_sidebar' => __('studio_ui_hide_sidebar', 'Hide editor sidebar for full-width canvas'),
        'show_panel' => __('studio_ui_show_panel', 'Show Panel'),
        'full_canvas' => __('studio_ui_full_canvas', 'Full Canvas'),
        'op_update_section' => __('studio_ui_op_update_section', 'Update section'),
        'op_edit_block' => __('studio_ui_op_edit_block', 'Edit {type}'),
        'mobile_nav' => __('studio_ui_mobile_nav', 'Mobile Navigation'),
        'dock_blocks' => __('studio_ui_dock_blocks', 'Blocks'),
        'dock_edit' => __('studio_ui_dock_edit', 'Edit'),
        'dock_theme' => __('studio_ui_dock_theme', 'Theme'),
        'dock_preview' => __('studio_ui_dock_preview', 'Preview'),
        'dock_more' => __('studio_ui_dock_more', 'More'),
        'dismiss_error' => __('studio_ui_dismiss_error', 'Dismiss error'),
        'dismiss' => __('studio_ui_dismiss', 'Dismiss'),
        'more_subtitle' => __('studio_ui_more_subtitle', 'Additional tools and settings for your page'),
        'more_settings_label' => __('studio_ui_more_settings_label', 'More Settings'),
        'close_settings' => __('studio_ui_close_settings', 'Close settings'),
        'more_page_settings' => __('studio_ui_more_page_settings', 'Page settings'),
        'more_page_settings_desc' => __('studio_ui_more_page_settings_desc', 'Title, slug, meta and basic settings'),
        'more_seo_desc' => __('studio_ui_more_seo_desc', 'Search engine optimization'),
        'more_page_bg' => __('studio_ui_more_page_bg', 'Page background'),
        'more_page_bg_desc' => __('studio_ui_more_page_bg_desc', 'Set background for this page'),
        'more_page_layout' => __('studio_ui_more_page_layout', 'Page layout'),
        'more_page_layout_desc' => __('studio_ui_more_page_layout_desc', 'Container, width and spacing'),
        'more_duplicate_page' => __('studio_ui_more_duplicate_page', 'Duplicate page'),
        'more_duplicate_page_desc' => __('studio_ui_more_duplicate_page_desc', 'Create a copy of this page'),
        'more_delete_page' => __('studio_ui_more_delete_page', 'Delete page'),
        'more_delete_page_desc' => __('studio_ui_more_delete_page_desc', 'Remove this page permanently'),
        'more_project' => __('studio_ui_more_project', 'Project'),
        'more_layers_desc' => __('studio_ui_more_layers_desc', 'View and manage page structure'),
        'more_media' => __('studio_ui_more_media', 'Media library'),
        'more_media_desc' => __('studio_ui_more_media_desc', 'Manage your images and files'),
        'more_reusable' => __('studio_ui_more_reusable', 'Reusable blocks'),
        'more_reusable_desc' => __('studio_ui_more_reusable_desc', 'Manage saved blocks'),
        'more_global' => __('studio_ui_more_global', 'Global components'),
        'more_global_desc' => __('studio_ui_more_global_desc', 'Manage site-wide components'),
        'more_history_group' => __('studio_ui_more_history_group', 'History & Collaboration'),
        'more_version_history' => __('studio_ui_more_version_history', 'Version history'),
        'more_version_history_desc' => __('studio_ui_more_version_history_desc', 'View and restore past versions'),
        'more_import_export' => __('studio_ui_more_import_export', 'Import & Export'),
        'more_import_export_desc' => __('studio_ui_more_import_export_desc', 'Export project package or HTML'),
        'more_dev_group' => __('studio_ui_more_dev_group', 'Developer & Advanced'),
        'more_custom_code' => __('studio_ui_more_custom_code', 'Custom code'),
        'more_custom_code_desc' => __('studio_ui_more_custom_code_desc', 'Add custom CSS, JS or head code'),
        'more_integrations' => __('studio_ui_more_integrations', 'Integrations'),
        'more_integrations_desc' => __('studio_ui_more_integrations_desc', 'Connect third-party services'),
        'more_shortcuts_desc' => __('studio_ui_more_shortcuts_desc', 'View all shortcuts'),
        'more_help' => __('studio_ui_more_help', 'Help & support'),
        'more_help_desc' => __('studio_ui_more_help_desc', 'Documentation and guides'),
        'more_seo' => __('studio_ui_more_seo', 'SEO'),
        'theme_label' => __('studio_ui_theme_label', 'Theme Design System'),
        'theme_subtitle' => __('studio_ui_theme_subtitle', 'Manage your site\'s global design system'),
        'close_theme' => __('studio_ui_close_theme', 'Close theme settings'),
        'theme_brand_identity' => __('studio_ui_theme_brand_identity', 'Brand identity'),
        'theme_brand_desc' => __('studio_ui_theme_brand_desc', 'Set your brand name, logo and general appearance.'),
        'theme_change_logo' => __('studio_ui_theme_change_logo', 'Change logo'),
        'theme_remove_logo' => __('studio_ui_theme_remove_logo', 'Remove logo'),
        'theme_site_name' => __('studio_ui_theme_site_name', 'Site name'),
        'theme_tagline' => __('studio_ui_theme_tagline', 'Tagline'),
        'theme_change_favicon' => __('studio_ui_theme_change_favicon', 'Change favicon'),
        'theme_remove_favicon' => __('studio_ui_theme_remove_favicon', 'Remove favicon'),
        'theme_palette' => __('studio_ui_theme_palette', 'Color palette'),
        'theme_palette_desc' => __('studio_ui_theme_palette_desc', 'Define your global colors and brand palette.'),
        'theme_color_mode' => __('studio_ui_theme_color_mode', 'Color mode'),
        'theme_type_desc' => __('studio_ui_theme_type_desc', 'Set your global fonts and text styles.'),
        'theme_heading_font' => __('studio_ui_theme_heading_font', 'Heading font'),
        'theme_body_font' => __('studio_ui_theme_body_font', 'Body font'),
        'theme_saving' => __('studio_ui_theme_saving', 'Saving...'),
        'theme_apply' => __('studio_ui_theme_apply', 'Apply changes'),
        'theme_typography' => __('studio_ui_theme_typography', 'Typography'),
        'theme_logo' => __('studio_ui_theme_logo', 'Logo'),
        'theme_favicon' => __('studio_ui_theme_favicon', 'Favicon'),
        'theme_tab_brand' => __('studio_ui_theme_tab_brand', 'Brand'),
        'theme_tab_colors' => __('studio_ui_theme_tab_colors', 'Colors'),
        'theme_tab_buttons' => __('studio_ui_theme_tab_buttons', 'Buttons'),
        'theme_tab_spacing' => __('studio_ui_theme_tab_spacing', 'Spacing'),
        'theme_tab_components' => __('studio_ui_theme_tab_components', 'Components'),
        'swatch_primary' => __('studio_ui_swatch_primary', 'Primary'),
        'swatch_secondary' => __('studio_ui_swatch_secondary', 'Secondary'),
        'swatch_background' => __('studio_ui_swatch_background', 'Background'),
        'swatch_surface' => __('studio_ui_swatch_surface', 'Surface'),
        'swatch_border' => __('studio_ui_swatch_border', 'Border'),
        'swatch_text' => __('studio_ui_swatch_text', 'Text'),
        'theme_mode_light' => __('studio_ui_theme_mode_light', 'Light'),
        'theme_mode_dark' => __('studio_ui_theme_mode_dark', 'Dark'),
        'theme_mode_auto' => __('studio_ui_theme_mode_auto', 'Auto'),
        'pal_search_placeholder' => __('studio_ui_pal_search_placeholder', 'Search sections, elements...'),
        'pal_search_label' => __('studio_ui_pal_search_label', 'Search sections and elements'),
        'pal_unfavorite' => __('studio_ui_pal_unfavorite', 'Remove favorite'),
        'pal_favorite_add' => __('studio_ui_pal_favorite_add', 'Add to favorites'),
        'pal_tab_sections' => __('studio_ui_pal_tab_sections', 'Sections'),
        'pal_tab_elements' => __('studio_ui_pal_tab_elements', 'Elements'),
        'pal_tab_components' => __('studio_ui_pal_tab_components', 'Components'),
        'pal_block_component_fallback' => __('studio_ui_pal_block_component_fallback', 'Block component'),
        'expand_panel' => __('studio_ui_expand_panel', 'Expand panel'),
        'collapse_panel' => __('studio_ui_collapse_panel', 'Collapse panel'),
        'page_home' => __('studio_ui_page_home', 'Home'),
        'page_work' => __('studio_ui_page_work', 'Projects'),
        'page_services' => __('studio_ui_page_services', 'Services'),
        'page_about' => __('studio_ui_page_about', 'About'),
        'page_contact' => __('studio_ui_page_contact', 'Contact'),
        'add' => __('studio_ui_add', 'Add'),
        'add_section' => __('studio_ui_add_section', 'Add section'),
        'ai_assistant' => __('studio_ui_ai_assistant', 'AI assistant'),
        'ai_badge' => __('studio_ui_ai_badge', 'AI draft'),
        'ai_review' => __('studio_ui_ai_review', 'Review AI draft'),
        'ai_review_hint' => __('studio_ui_ai_review_hint', 'An AI assistant prepared this draft revision. Nothing is live yet: compare it with the previous version, open the preview, then publish it yourself — or restore an earlier revision from History.'),
        'ai_review_stale' => __('studio_ui_ai_review_stale', 'The draft changed since this review was loaded. Reload to review the latest revision.'),
        'announce_component_created' => __('studio_ui_announce_component_created', 'Global component created'),
        'announce_component_detached' => __('studio_ui_announce_component_detached', 'Global component detached into local content'),
        'announce_component_inserted' => __('studio_ui_announce_component_inserted', 'Global component reference added'),
        'announce_component_published' => __('studio_ui_announce_component_published', 'Global component published'),
        'announce_conflict' => __('studio_ui_announce_conflict', 'Save rejected: the page changed on the server. Reload required.'),
        'announce_inserted' => __('studio_ui_announce_inserted', '{label} added'),
        'announce_moved' => __('studio_ui_announce_moved', '{label} moved'),
        'announce_published' => __('studio_ui_announce_published', 'Page published'),
        'announce_redo' => __('studio_ui_announce_redo', 'Redone'),
        'announce_rejected' => __('studio_ui_announce_rejected', 'That change was rejected and has been undone.'),
        'announce_removed' => __('studio_ui_announce_removed', '{label} deleted'),
        'announce_saved' => __('studio_ui_announce_saved', 'All changes saved'),
        'announce_selected' => __('studio_ui_announce_selected', '{label} selected'),
        'announce_template_applied' => __('studio_ui_announce_template_applied', 'Template applied'),
        'announce_template_deleted' => __('studio_ui_announce_template_deleted', 'Template deleted'),
        'announce_template_inserted' => __('studio_ui_announce_template_inserted', 'Template inserted'),
        'announce_template_saved' => __('studio_ui_announce_template_saved', 'Template saved'),
        'announce_tokens_saved' => __('studio_ui_announce_tokens_saved', 'Design tokens saved'),
        'announce_undo' => __('studio_ui_announce_undo', 'Undone'),
        'announce_viewport' => __('studio_ui_announce_viewport', 'Viewport: {label}'),
        'app_name' => __('studio_ui_app_name', 'Kohevo Studio'),
        'back_to_pages' => __('studio_ui_back_to_pages', 'Studio pages'),
        'cancel' => __('studio_ui_cancel', 'Cancel'),
        'close' => __('studio_ui_close', 'Close'),
        'collapse' => __('studio_ui_collapse', 'Collapse'),
        'collapse_all' => __('studio_ui_collapse_all', 'Collapse all'),
        'confirm_remove_section' => __('studio_ui_confirm_remove_section', 'Delete this section and all of its blocks?'),
        'conflict_body' => __('studio_ui_conflict_body', 'Your {count} most recent change(s) were not saved, because the page now has a newer revision on the server. Nothing was overwritten. Reload to continue from the newest version (your unsaved changes will be discarded).'),
        'conflict_reload' => __('studio_ui_conflict_reload', 'Reload latest version'),
        'conflict_title' => __('studio_ui_conflict_title', 'This page was changed somewhere else'),
        'duplicate' => __('studio_ui_duplicate', 'Duplicate'),
        'empty_page' => __('studio_ui_empty_page', 'This page is empty. Add a section to start.'),
        'error_server_error' => __('studio_ui_error_server_error', 'The server could not save this change. Retrying shortly.'),
        'expand' => __('studio_ui_expand', 'Expand'),
        'expand_all' => __('studio_ui_expand_all', 'Expand all'),
        'global_section_detach_confirm' => __('studio_ui_global_section_detach_confirm', 'Replace this reference with an independent local copy of the component content?'),
        'hide' => __('studio_ui_hide', 'Hide'),
        'history' => __('studio_ui_history', 'History'),
        'history_confirm' => __('studio_ui_history_confirm', 'Restore revision #{number}? This creates a new draft revision; published output does not change until you publish.'),
        'history_current' => __('studio_ui_history_current', 'Current'),
        'history_restore' => __('studio_ui_history_restore', 'Restore'),
        'history_title' => __('studio_ui_history_title', 'Revision history'),
        'import_done' => __('studio_ui_import_done', 'Imported into draft.'),
        'insert' => __('studio_ui_insert', 'Insert'),
        'insert_dialog_hint' => __('studio_ui_insert_dialog_hint', 'Fill in the required fields to add this block.'),
        'insert_dialog_title' => __('studio_ui_insert_dialog_title', 'Set up {label}'),
        'inspector' => __('studio_ui_inspector', 'Properties'),
        'library_confirm_apply' => __('studio_ui_library_confirm_apply', 'Replace the whole content of this page with the template "{name}"? Your current content stays in the revision history.'),
        'library_confirm_delete' => __('studio_ui_library_confirm_delete', 'Delete the template "{name}"? Pages keep the copies they already received.'),
        'load_failed' => __('studio_ui_load_failed', 'The builder could not load this page.'),
        'loading' => __('studio_ui_loading', 'Loading the builder…'),
        'lock_other' => __('studio_ui_lock_other', 'Someone else has this page open in the builder. Changes are protected by revision checks, but you may run into conflicts.'),
        'move_down' => __('studio_ui_move_down', 'Move down'),
        'move_up' => __('studio_ui_move_up', 'Move up'),
        'no_blocks_match' => __('studio_ui_no_blocks_match', 'No blocks match.'),
        'nothing_selected' => __('studio_ui_nothing_selected', 'Select a block or section on the canvas or in the structure to edit it.'),
        'outline_label' => __('studio_ui_outline_label', 'Page structure'),
        'packages' => __('studio_ui_packages', 'Import / Export'),
        'packages_title' => __('studio_ui_packages_title', 'Import or export a Studio package'),
        'panel_library' => __('studio_ui_panel_library', 'Library'),
        'panel_structure' => __('studio_ui_panel_structure', 'Structure'),
        'publish' => __('studio_ui_publish', 'Publish'),
        'redo' => __('studio_ui_redo', 'Redo'),
        'remove_item' => __('studio_ui_remove_item', 'Remove item'),
        'retry' => __('studio_ui_retry', 'Try again'),
        'search_blocks' => __('studio_ui_search_blocks', 'Search blocks'),
        'section' => __('studio_ui_section', 'Section'),
        'show' => __('studio_ui_show', 'Show'),
        'tab_style' => __('studio_ui_tab_style', 'Style'),
        'theme' => __('studio_ui_theme', 'Theme'),
        'theme_title' => __('studio_ui_theme_title', 'Design tokens'),
        'undo' => __('studio_ui_undo', 'Undo'),
        'unsaved_leave' => __('studio_ui_unsaved_leave', 'You have unsaved changes.'),
        'viewport' => __('studio_ui_viewport', 'Viewport'),
        'status_loading' => __('studio_ui_status_loading', 'Loading…'),
        'status_idle' => __('studio_ui_status_idle', 'All changes saved'),
        'status_saved' => __('studio_ui_status_saved', 'All changes saved'),
        'status_dirty' => __('studio_ui_status_dirty', 'Unsaved changes'),
        'status_saving' => __('studio_ui_status_saving', 'Saving…'),
        'status_error' => __('studio_ui_status_error', 'Not saved'),
        'status_conflict' => __('studio_ui_status_conflict', 'Conflict — not saved'),
        'save' => __('studio_ui_save', 'Save'),
        'preview' => __('studio_ui_preview', 'Preview'),
        'publishing_done' => __('studio_ui_publishing_done', 'Published.'),
        'desktop' => __('studio_ui_desktop', 'Desktop'),
        'tablet' => __('studio_ui_tablet', 'Tablet'),
        'mobile' => __('studio_ui_mobile', 'Mobile'),
        'panel_blocks' => __('studio_ui_panel_blocks', 'Blocks'),
        'rename' => __('studio_ui_rename', 'Rename'),
        'navigator' => __('studio_ui_navigator', 'Navigator'),
        'announce_duplicated' => __('studio_ui_announce_duplicated', '{label} duplicated'),
        'section_content' => __('studio_ui_section_content', 'Content'),
        'section_tokens' => __('studio_ui_section_tokens', 'Theme tokens'),
        'inspector_search' => __('studio_ui_inspector_search', 'Search settings'),
        'inspector_matches' => __('studio_ui_inspector_matches', '{n} matching sections'),
        'inspector_no_match' => __('studio_ui_inspector_no_match', 'No setting matches that search.'),
        'tab_content' => __('studio_ui_tab_content', 'Content'),
        'tab_advanced' => __('studio_ui_tab_advanced', 'Advanced'),
        'tab_responsive' => __('studio_ui_tab_responsive', 'Responsive'),
        'tab_visibility' => __('studio_ui_tab_visibility', 'Visibility'),
        'tab_data' => __('studio_ui_tab_data', 'Data'),
        'tab_motion' => __('studio_ui_tab_motion', 'Motion'),
        'tab_layout' => __('studio_ui_tab_layout', 'Layout'),
        'motion_entrance' => __('studio_ui_motion_entrance', 'Entrance animation'),
        'motion_entrance_hint' => __('studio_ui_motion_entrance_hint', 'How this block appears when the page loads.'),
        'motion_timing' => __('studio_ui_motion_timing', 'Timing'),
        'motion_duration' => __('studio_ui_motion_duration', 'Duration'),
        'motion_delay' => __('studio_ui_motion_delay', 'Delay'),
        'motion_easing' => __('studio_ui_motion_easing', 'Easing'),
        'motion_interaction' => __('studio_ui_motion_interaction', 'Interaction'),
        'motion_interaction_hint' => __('studio_ui_motion_interaction_hint', 'Runs when the visitor hovers, focuses, or scrolls to this block.'),
        'motion_none' => __('studio_ui_motion_none', 'None'),
        'motion_scroll_hint' => __('studio_ui_motion_scroll_hint', 'Continuous scroll tracking needs the Studio runtime and is not animated yet.'),
        'motion_reduced_note' => __('studio_ui_motion_reduced_note', 'Visitors who prefer reduced motion see this block without animation.'),
        'classes_label' => __('studio_ui_classes_label', 'CSS Classes'),
        'classes_hint' => __('studio_ui_classes_hint', 'Space-separated class names for custom styling.'),
        'attributes_label' => __('studio_ui_attributes_label', 'Custom Attributes'),
        'attributes_hint' => __('studio_ui_attributes_hint', 'Custom HTML data-* or ARIA attributes.'),
        'z_index_label' => __('studio_ui_z_index_label', 'Z-Index'),
        'typography' => __('studio_ui_typography', 'Typography'),
        'font_size' => __('studio_ui_font_size', 'Font Size'),
        'font_weight' => __('studio_ui_font_weight', 'Font Weight'),
        'text_transform' => __('studio_ui_text_transform', 'Text Transform'),
        'line_height' => __('studio_ui_line_height', 'Line Height'),
        'letter_spacing' => __('studio_ui_letter_spacing', 'Letter Spacing'),
        'text_color' => __('studio_ui_text_color', 'Text Color'),
        'border' => __('studio_ui_border', 'Border'),
        'border_style' => __('studio_ui_border_style', 'Border Style'),
        'border_width' => __('studio_ui_border_width', 'Border Width'),
        'border_color' => __('studio_ui_border_color', 'Border Color'),
        'border_radius' => __('studio_ui_border_radius', 'Border Radius'),
        'box_shadow' => __('studio_ui_box_shadow', 'Box Shadow'),
        'shadow_custom_hint' => __('studio_ui_shadow_custom_hint', 'A CSS box-shadow value, e.g. 0 10px 25px rgba(0,0,0,.15).'),
        'invalid_css_value' => __('studio_ui_invalid_css_value', 'Not a valid value. Use a length like 1.5rem or 12px, a colour like #e8734a, or leave it empty to inherit.'),
        'background_label' => __('studio_ui_background_label', 'Background'),
        'background_color' => __('studio_ui_background_color', 'Background Colour'),
        'gradient' => __('studio_ui_gradient', 'Gradient'),
        'gradient_from' => __('studio_ui_gradient_from', 'From'),
        'gradient_to' => __('studio_ui_gradient_to', 'To'),
        'gradient_angle' => __('studio_ui_gradient_angle', 'Angle'),
        'gradient_hint' => __('studio_ui_gradient_hint', 'A two-colour linear gradient. Pick the colours and the direction.'),
        'dimensions_label' => __('studio_ui_dimensions_label', 'Dimensions'),
        'dimension_width' => __('studio_ui_dimension_width', 'Width'),
        'dimension_min_height' => __('studio_ui_dimension_min_height', 'Min Height'),
        'dimension_max_width' => __('studio_ui_dimension_max_width', 'Max Width'),
        'opacity_label' => __('studio_ui_opacity_label', 'Opacity'),
        'font_family' => __('studio_ui_font_family', 'Font Family'),
        'device_overrides' => __('studio_ui_device_overrides', 'Device Overrides'),
        'hide_on_desktop' => __('studio_ui_hide_on_desktop', 'Hide on Desktop'),
        'hide_on_tablet' => __('studio_ui_hide_on_tablet', 'Hide on Tablet'),
        'hide_on_mobile' => __('studio_ui_hide_on_mobile', 'Hide on Mobile'),
        'page_settings' => __('studio_ui_page_settings', 'Page settings'),
        'seo' => __('studio_ui_seo', 'Search appearance'),
        'seo_count' => __('studio_ui_seo_count', '{count} / {max}'),
        'indent' => __('studio_ui_indent', 'Move into container above'),
        'outdent' => __('studio_ui_outdent', 'Move out of container'),
        'remove' => __('studio_ui_remove', 'Delete'),
        'none' => __('studio_ui_none', 'None'),
        'inherit' => __('studio_ui_inherit', 'Inherit'),
        'choose_image' => __('studio_ui_choose_image', 'Choose image'),
        'media_id' => __('studio_ui_media_id', 'Media ID'),
        'alt_text' => __('studio_ui_alt_text', 'Alternative text'),
        'focal_point' => __('studio_ui_focal_point', 'Focal point'),
        'link_label' => __('studio_ui_link_label', 'Label'),
        'link_href' => __('studio_ui_link_href', 'Address'),
        'link_new_tab' => __('studio_ui_link_new_tab', 'Open in a new tab'),
        'add_item' => __('studio_ui_add_item', 'Add item'),
        'item' => __('studio_ui_item', 'Item'),
        'devices' => __('studio_ui_devices', 'Show on'),
        'audience' => __('studio_ui_audience', 'Audience'),
        'align' => __('studio_ui_align', 'Alignment'),
        'columns' => __('studio_ui_columns', 'Columns'),
        'padding_y' => __('studio_ui_padding_y', 'Vertical padding'),
        'width' => __('studio_ui_width', 'Width'),
        'gap' => __('studio_ui_gap', 'Gap'),
        'background' => __('studio_ui_background', 'Background'),
        'provider' => __('studio_ui_provider', 'Data source'),
        'bindings_hint' => __('studio_ui_bindings_hint', 'This block shows live data from an installed module.'),
        'editing_at' => __('studio_ui_editing_at', 'Editing at'),
        'unavailable_block' => __('studio_ui_unavailable_block', 'Unknown block'),
        'announce_failed' => __('studio_ui_announce_failed', 'Saving failed. Your changes are kept and will be retried.'),
        'field_required' => __('studio_ui_field_required', 'This field is required.'),
        'field_too_long' => __('studio_ui_field_too_long', 'This is too long.'),
        'field_too_short' => __('studio_ui_field_too_short', 'This is too short.'),
        'field_number' => __('studio_ui_field_number', 'Enter a number.'),
        'field_integer' => __('studio_ui_field_integer', 'Enter a whole number.'),
        'field_too_small' => __('studio_ui_field_too_small', 'This number is too small.'),
        'field_too_large' => __('studio_ui_field_too_large', 'This number is too large.'),
        'field_url' => __('studio_ui_field_url', 'Enter a safe address (https://…, /path, #anchor, mailto: or tel:).'),
        'field_link_label' => __('studio_ui_field_link_label', 'A link needs a label.'),
        'field_media' => __('studio_ui_field_media', 'Choose an image.'),
        'field_too_many' => __('studio_ui_field_too_many', 'Too many items.'),
        'library_templates' => __('studio_ui_library_templates', 'Templates'),
        'library_page_templates' => __('studio_ui_library_page_templates', 'Page templates'),
        'library_section_presets' => __('studio_ui_library_section_presets', 'Section presets'),
        'library_block_presets' => __('studio_ui_library_block_presets', 'Block presets'),
        'library_header_presets' => __('studio_ui_library_header_presets', 'Header presets'),
        'library_footer_presets' => __('studio_ui_library_footer_presets', 'Footer presets'),
        'library_components' => __('studio_ui_library_components', 'Global components'),
        'library_empty_templates' => __('studio_ui_library_empty_templates', 'No templates yet. Save a page, section or block as a template to reuse it.'),
        'library_empty_components' => __('studio_ui_library_empty_components', 'No global components yet. Turn a section into a global component to reuse it live on several pages.'),
        'library_system' => __('studio_ui_library_system', 'System'),
        'library_apply' => __('studio_ui_library_apply', 'Apply to page'),
        'library_insert' => __('studio_ui_library_insert', 'Insert copy'),
        'library_insert_ref' => __('studio_ui_library_insert_ref', 'Insert reference'),
        'library_save_template' => __('studio_ui_library_save_template', 'Save as template…'),
        'library_new_component' => __('studio_ui_library_new_component', 'New global component…'),
        'library_delete' => __('studio_ui_library_delete', 'Delete'),
        'library_usage' => __('studio_ui_library_usage', 'Used on {count} page(s)'),
        'library_summary' => __('studio_ui_library_summary', '{sections} section(s), {blocks} block(s)'),
        'library_edit_component' => __('studio_ui_library_edit_component', 'Edit component'),
        'library_publish_component' => __('studio_ui_library_publish_component', 'Publish component'),
        'library_component_unpublished' => __('studio_ui_library_component_unpublished', 'Not published yet — pages show it only once it is published.'),
        'library_component_published' => __('studio_ui_library_component_published', 'Published'),
        'library_component_changes' => __('studio_ui_library_component_changes', 'Published · unpublished changes'),
        'save_template_title' => __('studio_ui_save_template_title', 'Save as template'),
        'save_template_hint' => __('studio_ui_save_template_hint', 'Templates are reusable copies: inserting one later puts an independent copy into the page.'),
        'template_name' => __('studio_ui_template_name', 'Name'),
        'template_key' => __('studio_ui_template_key', 'Key'),
        'template_type' => __('studio_ui_template_type', 'Template type'),
        'template_category' => __('studio_ui_template_category', 'Category'),
        'template_description' => __('studio_ui_template_description', 'Description'),
        'template_thumbnail' => __('studio_ui_template_thumbnail', 'Thumbnail (media)'),
        'template_replace_existing' => __('studio_ui_template_replace_existing', 'A template with this key already exists and will be replaced.'),
        'template_scope_page' => __('studio_ui_template_scope_page', 'Whole page'),
        'template_scope_section' => __('studio_ui_template_scope_section', 'Selected section'),
        'template_scope_block' => __('studio_ui_template_scope_block', 'Selected block'),
        'template_scope_header' => __('studio_ui_template_scope_header', 'This site header'),
        'template_scope_footer' => __('studio_ui_template_scope_footer', 'This site footer'),
        'template_needs_selection' => __('studio_ui_template_needs_selection', 'Select a section or block to save it as a preset.'),
        'component_title' => __('studio_ui_component_title', 'New global component'),
        'component_hint' => __('studio_ui_component_hint', 'A global component is edited once and shown live on every page that references it. Pages render its published version.'),
        'component_name' => __('studio_ui_component_name', 'Name'),
        'component_slug' => __('studio_ui_component_slug', 'Identifier (slug)'),
        'component_from_section' => __('studio_ui_component_from_section', 'Move the selected section into the component and replace it with a live reference'),
        'component_blank' => __('studio_ui_component_blank', 'Start empty'),
        'component_create' => __('studio_ui_component_create', 'Create'),
        'component_open_after' => __('studio_ui_component_open_after', 'Open the component in the builder after creating it'),
        'global_section_title' => __('studio_ui_global_section_title', 'Global component'),
        'global_section_body' => __('studio_ui_global_section_body', 'This section shows a global component. Its content is edited in the component, not here.'),
        'global_section_missing' => __('studio_ui_global_section_missing', 'The referenced component is missing or not accessible.'),
        'global_section_detach' => __('studio_ui_global_section_detach', 'Detach (make a local copy)'),
        'chrome_title' => __('studio_ui_chrome_title', 'Header & footer'),
        'chrome_header' => __('studio_ui_chrome_header', 'Header'),
        'chrome_footer' => __('studio_ui_chrome_footer', 'Footer'),
        'chrome_mode_inherit' => __('studio_ui_chrome_mode_inherit', 'Site default'),
        'chrome_mode_custom' => __('studio_ui_chrome_mode_custom', 'Custom for this page'),
        'chrome_mode_hidden' => __('studio_ui_chrome_mode_hidden', 'Hidden'),
        'chrome_resolved_hidden' => __('studio_ui_chrome_resolved_hidden', 'Not shown on this page.'),
        'chrome_resolved_site' => __('studio_ui_chrome_resolved_site', 'Shows the site {region} "{title}".'),
        'chrome_resolved_custom' => __('studio_ui_chrome_resolved_custom', 'Shows this page\'s own {region} "{title}".'),
        'chrome_resolved_builtin' => __('studio_ui_chrome_resolved_builtin', 'Shows the built-in {region} (site name and logo) until a site {region} is published.'),
        'chrome_custom_missing' => __('studio_ui_chrome_custom_missing', 'No published {region} named after this page yet; the site default is shown instead.'),
        'chrome_edit_site' => __('studio_ui_chrome_edit_site', 'Edit site {region}'),
        'chrome_create_site' => __('studio_ui_chrome_create_site', 'Create site {region}'),
        'chrome_edit_custom' => __('studio_ui_chrome_edit_custom', 'Edit this page\'s {region}'),
        'chrome_create_custom' => __('studio_ui_chrome_create_custom', 'Create a {region} for this page'),
        'chrome_not_chromed' => __('studio_ui_chrome_not_chromed', 'This document type has no header or footer of its own.'),
        'chrome_draft_note' => __('studio_ui_chrome_draft_note', '(has unpublished changes)'),
        'theme_hint' => __('studio_ui_theme_hint', 'Tokens are the only styling values pages can reference. Values are validated: colours, lengths, shadows and font families only.'),
        'theme_branding_note' => __('studio_ui_theme_branding_note', 'Site branding (colours and fonts from Settings › Branding) applies first; Studio tokens override it for Studio pages.'),
        'theme_branding_link' => __('studio_ui_theme_branding_link', 'Open site branding settings'),
        'theme_source_default' => __('studio_ui_theme_source_default', 'default'),
        'theme_source_branding' => __('studio_ui_theme_source_branding', 'from branding'),
        'theme_source_studio' => __('studio_ui_theme_source_studio', 'Studio override'),
        'theme_reset' => __('studio_ui_theme_reset', 'Use inherited'),
        'theme_save' => __('studio_ui_theme_save', 'Save tokens'),
        'theme_invalid' => __('studio_ui_theme_invalid', 'Some values were rejected. Fix the highlighted tokens.'),
        'theme_group' => __('studio_ui_theme_group', 'Token group'),
        'ai_review_title' => __('studio_ui_ai_review_title', 'Review the AI-proposed draft'),
        'ai_review_no_ai' => __('studio_ui_ai_review_no_ai', 'The current draft was not produced by an AI assistant.'),
        'ai_review_base' => __('studio_ui_ai_review_base', 'Compared with revision #{number} ({kind})'),
        'ai_review_base_empty' => __('studio_ui_ai_review_base_empty', 'Compared with an empty page'),
        'ai_review_proposed' => __('studio_ui_ai_review_proposed', 'Proposed revision #{number} (AI draft)'),
        'ai_review_changes' => __('studio_ui_ai_review_changes', 'Changes'),
        'ai_review_no_changes' => __('studio_ui_ai_review_no_changes', 'No differences.'),
        'ai_review_preview' => __('studio_ui_ai_review_preview', 'Open preview of this exact revision'),
        'ai_review_publish' => __('studio_ui_ai_review_publish', 'Publish this revision'),
        'ai_review_publish_hint' => __('studio_ui_ai_review_publish_hint', 'Publishing is bound to revision #{number}. If the draft changes before you click, the server refuses with a conflict and nothing goes live.'),
        'ai_review_no_permission' => __('studio_ui_ai_review_no_permission', 'You do not have permission to publish. Ask a publisher to review this draft.'),
        'ai_review_dependency' => __('studio_ui_ai_review_dependency', 'Publishing this shared content updates {count} page(s) that use it.'),
        'ai_review_published' => __('studio_ui_ai_review_published', 'This revision is already published.'),
        'count_sections_added' => __('studio_ui_count_sections_added', '{count} section(s) added'),
        'count_sections_removed' => __('studio_ui_count_sections_removed', '{count} section(s) removed'),
        'count_sections_moved' => __('studio_ui_count_sections_moved', '{count} section(s) moved'),
        'count_sections_updated' => __('studio_ui_count_sections_updated', '{count} section(s) updated'),
        'count_blocks_added' => __('studio_ui_count_blocks_added', '{count} block(s) added'),
        'count_blocks_removed' => __('studio_ui_count_blocks_removed', '{count} block(s) removed'),
        'count_blocks_moved' => __('studio_ui_count_blocks_moved', '{count} block(s) moved'),
        'count_blocks_updated' => __('studio_ui_count_blocks_updated', '{count} block(s) updated'),
        'count_settings_changed' => __('studio_ui_count_settings_changed', 'page settings changed'),
        'count_seo_changed' => __('studio_ui_count_seo_changed', 'search appearance changed'),
        'count_template_changed' => __('studio_ui_count_template_changed', 'template changed'),
        'packages_tab_export' => __('studio_ui_packages_tab_export', 'Export'),
        'packages_tab_import' => __('studio_ui_packages_tab_import', 'Import'),
        'export_hint' => __('studio_ui_export_hint', 'Download this page as a Kohevo Studio JSON package. Images travel as references only — no files are included.'),
        'export_components' => __('studio_ui_export_components', 'Include the global components this page uses'),
        'export_template' => __('studio_ui_export_template', 'Include the template this page uses'),
        'export_tokens' => __('studio_ui_export_tokens', 'Include this site\'s design token overrides'),
        'export_download' => __('studio_ui_export_download', 'Download package'),
        'export_done' => __('studio_ui_export_done', 'Package downloaded.'),
        'import_hint' => __('studio_ui_import_hint', 'Choose a Kohevo Studio package (.json). Analyse it first: nothing is changed until you import, and imports only ever create drafts — nothing is published.'),
        'import_file' => __('studio_ui_import_file', 'Package file'),
        'import_mode' => __('studio_ui_import_mode', 'Import as'),
        'import_mode_create' => __('studio_ui_import_mode_create', 'New draft page(s)'),
        'import_mode_replace' => __('studio_ui_import_mode_replace', 'Replace this page\'s draft (the published page is not touched)'),
        'import_tokens' => __('studio_ui_import_tokens', 'Also replace this site\'s design tokens (they apply to the live site immediately)'),
        'import_analyze' => __('studio_ui_import_analyze', 'Analyse (dry run)'),
        'import_commit' => __('studio_ui_import_commit', 'Import into draft'),
        'import_reanalyze' => __('studio_ui_import_reanalyze', 'The inputs or the page changed since the analysis. Analyse again before importing.'),
        'import_ready' => __('studio_ui_import_ready', 'Ready to import.'),
        'import_blocked' => __('studio_ui_import_blocked', 'This package cannot be imported as it is.'),
        'import_summary' => __('studio_ui_import_summary', '{pages} page(s), {components} component(s), {templates} template(s), {tokens} token group(s) · {sections} sections, {blocks} blocks · {errors} error(s), {warnings} warning(s)'),
        'import_errors' => __('studio_ui_import_errors', 'Errors'),
        'import_warnings' => __('studio_ui_import_warnings', 'Warnings'),
        'import_plan' => __('studio_ui_import_plan', 'What will happen'),
        'import_open' => __('studio_ui_import_open', 'Open'),
        'import_components_draft' => __('studio_ui_import_components_draft', 'Imported global components are drafts: pages show them only after they are published.'),
        'package_empty' => __('studio_ui_package_empty', 'The file is empty.'),
        'package_too_large' => __('studio_ui_package_too_large', 'This package is too large.'),
        'package_not_json' => __('studio_ui_package_not_json', 'This file is not valid JSON.'),
        'package_not_studio' => __('studio_ui_package_not_studio', 'This is not a Kohevo Studio package.'),
        'plan_replace_token_group' => __('studio_ui_plan_replace_token_group', 'Replace design tokens of group “{name}”'),
        'plan_create_global_component' => __('studio_ui_plan_create_global_component', 'Create global component “{name}” (draft)'),
        'plan_create_template' => __('studio_ui_plan_create_template', 'Create template “{name}”'),
        'plan_create_page' => __('studio_ui_plan_create_page', 'Create draft page /{name}'),
        'plan_replace_draft' => __('studio_ui_plan_replace_draft', 'Replace this page\'s draft'),
        'error_validation_error' => __('studio_ui_error_validation_error', 'That change was rejected because it is not valid.'),
        'error_authentication_error' => __('studio_ui_error_authentication_error', 'Your session has ended. Sign in again to keep editing.'),
        'error_authorization_error' => __('studio_ui_error_authorization_error', 'You do not have permission to do this.'),
        'error_entitlement_error' => __('studio_ui_error_entitlement_error', 'Kohevo Studio is not available on this site.'),
        'error_csrf_error' => __('studio_ui_error_csrf_error', 'The security check failed. Reload the builder.'),
        'error_not_found' => __('studio_ui_error_not_found', 'This page or revision no longer exists.'),
        'error_concurrency_conflict' => __('studio_ui_error_concurrency_conflict', 'This page was changed elsewhere.'),
        'error_rate_limited' => __('studio_ui_error_rate_limited', 'Too many requests. Retrying shortly.'),
        'error_payload_too_large' => __('studio_ui_error_payload_too_large', 'This change is too large to save.'),
        'error_network_error' => __('studio_ui_error_network_error', 'Could not reach the server. Retrying shortly.'),
        'error_timeout' => __('studio_ui_error_timeout', 'The server took too long to answer. Retrying shortly.'),
        'change' => __('studio_ui_change', 'Change'),
        'rt_formatting' => __('studio_ui_rt_formatting', 'Formatting'),
        'rt_bold' => __('studio_ui_rt_bold', 'Bold'),
        'rt_italic' => __('studio_ui_rt_italic', 'Italic'),
        'rt_underline' => __('studio_ui_rt_underline', 'Underline'),
        'rt_bold_glyph' => __('studio_ui_rt_bold_glyph', 'B'),
        'rt_italic_glyph' => __('studio_ui_rt_italic_glyph', 'I'),
        'rt_underline_glyph' => __('studio_ui_rt_underline_glyph', 'U'),
        'rt_bulleted' => __('studio_ui_rt_bulleted', 'Bulleted list'),
        'rt_numbered' => __('studio_ui_rt_numbered', 'Numbered list'),
        'rt_link' => __('studio_ui_rt_link', 'Link'),
        'rt_remove_link' => __('studio_ui_rt_remove_link', 'Remove link'),
        'rt_link_prompt' => __('studio_ui_rt_link_prompt', 'Link address (https://…, /path, #anchor, mailto:, tel:)'),
        'fw_normal' => __('studio_ui_fw_normal', 'Normal (400)'),
        'fw_medium' => __('studio_ui_fw_medium', 'Medium (500)'),
        'fw_semibold' => __('studio_ui_fw_semibold', 'Semibold (600)'),
        'fw_bold' => __('studio_ui_fw_bold', 'Bold (700)'),
        'fw_extrabold' => __('studio_ui_fw_extrabold', 'Extra Bold (800)'),
        'tt_uppercase' => __('studio_ui_tt_uppercase', 'UPPERCASE'),
        'tt_lowercase' => __('studio_ui_tt_lowercase', 'lowercase'),
        'tt_capitalize' => __('studio_ui_tt_capitalize', 'Capitalize'),
        'classes_placeholder' => __('studio_ui_classes_placeholder', 'e.g. my-custom-class hero-banner'),
        'bg_type' => __('studio_ui_bg_type', 'Background type'),
        'bg_mode_image' => __('studio_ui_bg_mode_image', 'Image'),
        'bg_mode_color' => __('studio_ui_bg_mode_color', 'Color'),
        'bg_mode_gradient' => __('studio_ui_bg_mode_gradient', 'Gradient'),
        'bg_mode_video' => __('studio_ui_bg_mode_video', 'Video'),
        'bg_image_url' => __('studio_ui_bg_image_url', 'Image URL'),
        'bg_video_url' => __('studio_ui_bg_video_url', 'Video URL (MP4 / WebM)'),
        'url_placeholder_assets' => __('studio_ui_url_placeholder_assets', 'https://... or /assets/...'),
        'url_placeholder_path' => __('studio_ui_url_placeholder_path', 'https://… or /path'),
        'bg_fit' => __('studio_ui_bg_fit', 'Fit'),
        'bg_position' => __('studio_ui_bg_position', 'Position'),
        'fit_cover' => __('studio_ui_fit_cover', 'Cover'),
        'fit_contain' => __('studio_ui_fit_contain', 'Contain'),
        'fit_fill' => __('studio_ui_fit_fill', 'Fill'),
        'bg_image' => __('studio_ui_bg_image', 'Background image'),
        'bg_repeat' => __('studio_ui_bg_repeat', 'Repeat'),
        'repeat_no_repeat' => __('studio_ui_repeat_no_repeat', 'Do not repeat'),
        'repeat_repeat' => __('studio_ui_repeat_repeat', 'Repeat'),
        'repeat_repeat_x' => __('studio_ui_repeat_repeat_x', 'Repeat horizontally'),
        'repeat_repeat_y' => __('studio_ui_repeat_repeat_y', 'Repeat vertically'),
        'bg_overlay' => __('studio_ui_bg_overlay', 'Overlay colour'),
        'fit_auto' => __('studio_ui_fit_auto', 'Original'),
        'pos_center_center' => __('studio_ui_pos_center_center', 'Center center'),
        'pos_top_center' => __('studio_ui_pos_top_center', 'Top center'),
        'pos_bottom_center' => __('studio_ui_pos_bottom_center', 'Bottom center'),
        'pos_center_left' => __('studio_ui_pos_center_left', 'Center left'),
        'pos_center_right' => __('studio_ui_pos_center_right', 'Center right'),
        'bs_solid' => __('studio_ui_bs_solid', 'Solid'),
        'bs_dashed' => __('studio_ui_bs_dashed', 'Dashed'),
        'bs_dotted' => __('studio_ui_bs_dotted', 'Dotted'),
        'bs_double' => __('studio_ui_bs_double', 'Double'),
        'size_sm' => __('studio_ui_size_sm', 'Small'),
        'size_md' => __('studio_ui_size_md', 'Medium'),
        'size_lg' => __('studio_ui_size_lg', 'Large'),
        'size_xl' => __('studio_ui_size_xl', 'XL'),
        'size_2xl' => __('studio_ui_size_2xl', '2XL'),
        'size_full_pill' => __('studio_ui_size_full_pill', 'Full (Pill)'),
        'focal_image_label' => __('studio_ui_focal_image_label', 'Image focal point'),
        'focal_preview' => __('studio_ui_focal_preview', 'Focal preview'),
        'preset_cat_hero' => __('studio_ui_preset_cat_hero', 'Hero'),
        'preset_cat_features' => __('studio_ui_preset_cat_features', 'Features'),
        'preset_cat_content' => __('studio_ui_preset_cat_content', 'Content'),
        'preset_cat_social_proof' => __('studio_ui_preset_cat_social_proof', 'Social proof'),
        'preset_cat_pricing' => __('studio_ui_preset_cat_pricing', 'Pricing'),
        'preset_cat_cta' => __('studio_ui_preset_cat_cta', 'Call to action'),
        'preset_cat_team' => __('studio_ui_preset_cat_team', 'Team'),
        'preset_cat_contact' => __('studio_ui_preset_cat_contact', 'Contact'),
        'preset_cat_footer' => __('studio_ui_preset_cat_footer', 'Footer'),
        'pal_no_sections' => __('studio_ui_pal_no_sections', 'No sections match.'),
        'pal_insert_section' => __('studio_ui_pal_insert_section', 'Insert section {name}'),
        'pal_presets_unavailable' => __('studio_ui_pal_presets_unavailable', 'Sections could not be loaded. Reload the builder to try again.'),
        'block_cat_layout' => __('studio_ui_block_cat_layout', 'Layout'),
        'block_cat_content' => __('studio_ui_block_cat_content', 'Content'),
        'block_cat_media' => __('studio_ui_block_cat_media', 'Media'),
        'block_cat_forms' => __('studio_ui_block_cat_forms', 'Forms'),
        'block_cat_business' => __('studio_ui_block_cat_business', 'Kohevo modules'),
        'block_cat_advanced' => __('studio_ui_block_cat_advanced', 'Advanced'),
        'block_cat_theme' => __('studio_ui_block_cat_theme', 'Theme'),
        'pal_all' => __('studio_ui_pal_all', 'All'),
        'pal_category_rail' => __('studio_ui_pal_category_rail', 'Categories'),
        'pal_view_all' => __('studio_ui_pal_view_all', 'View all ({count})'),
        'row_drag_handle' => __('studio_ui_row_drag_handle', 'Drag to reorder {label}'),
        'row_drag_hint' => __('studio_ui_row_drag_hint', 'Drag, or press the up and down arrow keys to move it.'),
        'nav_tools_label' => __('studio_ui_nav_tools_label', 'Page tools'),
        'row_menu' => __('studio_ui_row_menu', 'More actions for {label}'),
        'row_rename' => __('studio_ui_row_rename', 'Rename'),
        'row_move_up' => __('studio_ui_row_move_up', 'Move up'),
        'row_move_down' => __('studio_ui_row_move_down', 'Move down'),
        'row_save_library' => __('studio_ui_row_save_library', 'Save to library…'),
        'nav_partials_label' => __('studio_ui_nav_partials_label', 'Header and footer of this page'),
        'nav_partial_builtin' => __('studio_ui_nav_partial_builtin', 'Built-in'),
        'nav_partial_hidden' => __('studio_ui_nav_partial_hidden', 'Hidden on this page'),
        'nav_partial_custom' => __('studio_ui_nav_partial_custom', 'This page\'s own: {title}'),
        'nav_partial_site' => __('studio_ui_nav_partial_site', 'Shared by the site: {title}'),
        'nav_partial_edit' => __('studio_ui_nav_partial_edit', 'Edit {region}'),
        'nav_view_label' => __('studio_ui_nav_view_label', 'Layers or pages'),
        'nav_layers' => __('studio_ui_nav_layers', 'Layers'),
        'nav_pages' => __('studio_ui_nav_pages', 'Pages'),
        'nav_pages_loading' => __('studio_ui_nav_pages_loading', 'Loading pages…'),
        'nav_pages_empty' => __('studio_ui_nav_pages_empty', 'No pages yet.'),
        'nav_pages_failed' => __('studio_ui_nav_pages_failed', 'The pages could not be loaded.'),
        'nav_pages_list' => __('studio_ui_nav_pages_list', 'Pages of this site'),
        'nav_page_new' => __('studio_ui_nav_page_new', 'New page'),
        'nav_page_new_title' => __('studio_ui_nav_page_new_title', 'New page'),
        'nav_page_current' => __('studio_ui_nav_page_current', 'Current page'),
        'nav_page_open' => __('studio_ui_nav_page_open', 'Open {title}'),
        'nav_status_published' => __('studio_ui_nav_status_published', 'Published'),
        'nav_status_draft' => __('studio_ui_nav_status_draft', 'Draft'),
        'nav_status_changes' => __('studio_ui_nav_status_changes', 'Unpublished changes'),
        'nav_page_homepage' => __('studio_ui_nav_page_homepage', 'Homepage'),
        'nav_page_actions' => __('studio_ui_nav_page_actions', 'Actions for {title}'),
        'nav_page_rename' => __('studio_ui_nav_page_rename', 'Rename'),
        'nav_page_rename_title' => __('studio_ui_nav_page_rename_title', 'Rename page'),
        'nav_page_duplicate' => __('studio_ui_nav_page_duplicate', 'Duplicate'),
        'nav_page_dup_title' => __('studio_ui_nav_page_dup_title', 'Duplicate page'),
        'nav_page_dup_hint' => __('studio_ui_nav_page_dup_hint', 'Copies this page into a new draft. It is not published until you publish it.'),
        'nav_page_archive' => __('studio_ui_nav_page_archive', 'Archive'),
        'nav_page_archive_current' => __('studio_ui_nav_page_archive_current', 'The page you are editing cannot be archived here.'),
        'nav_page_name' => __('studio_ui_nav_page_name', 'Page name'),
        'nav_page_address' => __('studio_ui_nav_page_address', 'Address'),
        'nav_page_address_warn' => __('studio_ui_nav_page_address_warn', 'Changing the address of a published page changes its public URL.'),
        'nav_page_create' => __('studio_ui_nav_page_create', 'Create page'),
        'nav_page_save' => __('studio_ui_nav_page_save', 'Save'),
        'nav_page_copy_suffix' => __('studio_ui_nav_page_copy_suffix', ' (copy)'),
        'nav_page_archive_confirm' => __('studio_ui_nav_page_archive_confirm', 'Archive "{title}"? It leaves this list.'),
        'nav_page_archive_confirm_published' => __('studio_ui_nav_page_archive_confirm_published', 'Archive "{title}"? It is published, so it stops being served on your site.'),
        'nav_page_unsaved' => __('studio_ui_nav_page_unsaved', 'You have unsaved changes. Leave this page anyway?'),
        'nav_page_save_first' => __('studio_ui_nav_page_save_first', 'Wait for your changes to be saved before renaming the page you are editing.'),
        'nav_announce_created' => __('studio_ui_nav_announce_created', 'Page "{title}" created.'),
        'nav_announce_duplicated' => __('studio_ui_nav_announce_duplicated', 'Page "{title}" created as a draft.'),
        'nav_announce_renamed' => __('studio_ui_nav_announce_renamed', 'Page renamed to "{title}".'),
        'nav_announce_archived' => __('studio_ui_nav_announce_archived', 'Page "{title}" archived.'),
        'pal_reason_blocks_limit' => __('studio_ui_pal_reason_blocks_limit', 'This page has reached its block limit.'),
        'pal_reason_sections_limit' => __('studio_ui_pal_reason_sections_limit', 'This page has reached its section limit.'),
        'pal_reason_not_allowed' => __('studio_ui_pal_reason_not_allowed', 'This cannot go inside the selected item. Select a section instead.'),
        'pal_no_results' => __('studio_ui_pal_no_results', 'Nothing matches your search.'),
        'pal_search_results' => __('studio_ui_pal_search_results', 'Search results'),
        'pal_components_kohevo' => __('studio_ui_pal_components_kohevo', 'Kohevo components'),
        'pal_components_none_licensed' => __('studio_ui_pal_components_none_licensed', 'No Kohevo components are available on this site.'),
        'pal_components_none_global' => __('studio_ui_pal_components_none_global', 'No global components yet. Turn a section into one from the Library.'),
        'multi_select_hint' => __('studio_ui_multi_select_hint', 'Select a single layer to edit its properties. Use the Layers panel to lock, duplicate or remove the selection.'),
        'edit_inline' => __('studio_ui_edit_inline', 'Edit text'),
        'selection_toolbar' => __('studio_ui_selection_toolbar', 'Actions for the selected layer'),
        'fit' => __('studio_ui_fit', 'Fit'),
        'zoom_fit' => __('studio_ui_zoom_fit', 'Fit the canvas to the screen'),
        'zoom_in' => __('studio_ui_zoom_in', 'Zoom in'),
        'zoom_out' => __('studio_ui_zoom_out', 'Zoom out'),
        'zoom_level' => __('studio_ui_zoom_level', 'Canvas zoom'),
        'shortcuts_help' => __('studio_ui_shortcuts_help', 'Keyboard shortcuts'),
        'shortcuts_title' => __('studio_ui_shortcuts_title', 'Keyboard shortcuts'),
        'shortcut_undo' => __('studio_ui_shortcut_undo', 'Undo'),
        'shortcut_redo' => __('studio_ui_shortcut_redo', 'Redo'),
        'shortcut_save' => __('studio_ui_shortcut_save', 'Save draft'),
        'shortcut_search' => __('studio_ui_shortcut_search', 'Search Add (sections, elements)'),
        'shortcut_duplicate' => __('studio_ui_shortcut_duplicate', 'Duplicate the selection'),
        'shortcut_multi' => __('studio_ui_shortcut_multi', 'Add to the selection'),
        'shortcut_range' => __('studio_ui_shortcut_range', 'Select a range of layers'),
        'shortcut_rename' => __('studio_ui_shortcut_rename', 'Rename the layer (Layers panel)'),
        'shortcut_delete' => __('studio_ui_shortcut_delete', 'Remove the layer (Layers panel)'),
        'shortcut_deselect' => __('studio_ui_shortcut_deselect', 'Clear the selection'),
        'responsive_view' => __('studio_ui_responsive_view', 'Responsive view'),
        'responsive_view_hint' => __('studio_ui_responsive_view_hint', 'Pick a device size and show layout aids on the canvas'),
        'device_preset' => __('studio_ui_device_preset', 'Device'),
        'canvas_aids' => __('studio_ui_canvas_aids', 'Show on canvas'),
        'aid_outlines' => __('studio_ui_aid_outlines', 'Element outlines'),
        'aid_labels' => __('studio_ui_aid_labels', 'Section labels'),
        'aid_grid' => __('studio_ui_aid_grid', 'Column grid'),
        'aid_spacing' => __('studio_ui_aid_spacing', 'Spacing guides'),
        'aid_dark' => __('studio_ui_aid_dark', 'Dark mode preview'),
        'aid_unavailable' => __('studio_ui_aid_unavailable', 'Not available yet'),
        'chip_unsaved' => __('studio_ui_chip_unsaved', 'Unsaved'),
        'chip_saved' => __('studio_ui_chip_saved', 'Saved'),
        'chip_published' => __('studio_ui_chip_published', 'Published'),
        'bulk_remove_confirm' => __('studio_ui_bulk_remove_confirm', 'Remove {count} selected items?'),
        'clear_selection' => __('studio_ui_clear_selection', 'Clear'),
        'palette_dynamic' => __('studio_ui_palette_dynamic', 'Dynamic'),
        'palette_media' => __('studio_ui_palette_media', 'Media'),
        'palette_ai' => __('studio_ui_palette_ai', 'AI'),
        'dynamic_data_from' => __('studio_ui_dynamic_data_from', 'Data from'),
        'dynamic_page_context' => __('studio_ui_dynamic_page_context', 'Uses the current page or post'),
        'dynamic_note' => __('studio_ui_dynamic_note', 'These blocks read live data from your site. Studio only stores the connection; each module keeps its own data and your tenant boundary.'),
        'media_add_image' => __('studio_ui_media_add_image', 'Add an image from the media library'),
        'media_unavailable' => __('studio_ui_media_unavailable', 'The media library is not available to your account. Insert a media block and enter an image id.'),
        'media_note' => __('studio_ui_media_note', 'Only the image id is stored on the page, never a file path.'),
        'ai_panel_note' => __('studio_ui_ai_panel_note', 'The AI assistant prepares changes as a draft revision. Nothing goes live until you review and publish it yourself.'),
        'ai_unavailable' => __('studio_ui_ai_unavailable', 'The AI assistant is not enabled for your account.'),
        'lock_layer' => __('studio_ui_lock_layer', 'Lock'),
        'unlock_layer' => __('studio_ui_unlock_layer', 'Unlock'),
        'locked_by_parent' => __('studio_ui_locked_by_parent', 'Locked by a parent layer. Unlock the parent first.'),
        'layer_locked_note' => __('studio_ui_layer_locked_note', 'This layer is locked. Unlock it to edit, move, rename or remove it.'),
        'layer_locked_by_parent' => __('studio_ui_layer_locked_by_parent', 'A parent layer is locked, so this layer cannot be edited. Unlock the parent first.'),
        'announce_locked' => __('studio_ui_announce_locked', 'This layer is locked. Unlock it first.'),
        'announce_layer_locked' => __('studio_ui_announce_layer_locked', '{label} locked'),
        'announce_layer_unlocked' => __('studio_ui_announce_layer_unlocked', '{label} unlocked'),
        'announce_renamed' => __('studio_ui_announce_renamed', 'Renamed to {label}'),
        'layer_name_cleared' => __('studio_ui_layer_name_cleared', 'Layer name cleared'),
    ],
];
?><!DOCTYPE html>
<html lang="<?= e(\Slate\Services\I18n\I18n::currentLocale()) ?>">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="robots" content="noindex,nofollow">
<link rel="icon" href="data:,">
<title><?= e($sbTitle) ?> — <?= e(__('studio_builder', 'Kohevo Studio')) ?></title>
<link rel="stylesheet" href="<?= e(plugin_url('studio-builder', 'assets/builder/builder.css')) ?>?v=<?= e($sbVersion) ?>">
<?php if ($sbMediaPicker): ?>
<link rel="stylesheet" href="<?= e(plugin_url('media-library', 'assets/css/picker.css')) ?>">
<script src="<?= e(plugin_url('media-library', 'assets/js/picker.js')) ?>" defer></script>
<?php endif; ?>
<script type="application/json" id="sb-builder-boot"><?= json_encode($sbBoot, JSON_HEX_TAG | JSON_HEX_AMP | JSON_HEX_APOS | JSON_HEX_QUOT | JSON_UNESCAPED_SLASHES) ?></script>
<script type="module" src="<?= e(plugin_url('studio-builder', 'assets/builder/builder.js')) ?>?v=<?= e($sbVersion) ?>"></script>
</head>
<body class="sbx-body">
<div id="sb-builder-root">
  <noscript><?= e(__('studio_builder_needs_js', 'Kohevo Studio needs JavaScript enabled.')) ?></noscript>
  <p class="sbx-boot-loading" role="status"><?= e(__('studio_builder_loading', 'Loading the builder…')) ?></p>
</div>
</body>
</html>
